"""Tests for Prometheus metrics"""
from fastapi.testclient import TestClient
from app import app

client = TestClient(app)

def test_metrics_endpoint():
    response = client.get("/metrics")
    assert response.status_code == 200
    # Prometheus format
    assert "text/plain" in response.headers.get("content-type", "")

def test_metrics_contain_counter():
    response = client.get("/metrics")
    text = response.text.lower()
    assert "attacks_total" in text

def test_metrics_format():
    response = client.get("/metrics")
    lines = response.text.split("\n")
    # Should have prometheus header
    assert any("generated by prometheus" in l.lower() for l in lines)