apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
  
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    editable: true
    jsonData:
      database: honeypot
      user: honeypot
      secureJsonData:
        password: "demo"
    secureJsonFields:
      password:
        - GRAFANA_DB_PASSWORD